import Head from "next/head";
import { useState } from "react";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { SiTailwindcss, SiJavascript } from "react-icons/si";
import { FaCss3Alt } from "react-icons/fa";
import { FaReact } from "react-icons/fa";
import { TbBrandNextjs } from "react-icons/tb";
import { AiFillLinkedin, AiFillGithub, AiFillHtml5 } from "react-icons/ai";

import Image from "next/image";
import expenseTracker from "../public/expense-tracker-2.png";
import jaaro from "../public/jaaro-1.png";
import jobFinder from "../public/jobFinder-2.png";
import memeGen from "../public/meme-generator-1.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">PORTFOLIO</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className=" cursor-pointer text-xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">
              Nidal Mohammed
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Front-End Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              Front end developer skilled in react, js, css, html, next.js and
              tailwind css.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://github.com/nidal23">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/nidal-mohammed-959829193/">
              <AiFillLinkedin />
            </a>
          </div>
          {/* <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div> */}
        </section>

        <section>
          <div>
            <h3 className="text-3xl font-bold py-6 text-center dark:text-white">
              My Skills
            </h3>
          </div>
          <div className="text-5xl flex flex-wrap justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <FaReact />
            <SiJavascript />
            <AiFillHtml5 />
            <FaCss3Alt />
            <SiTailwindcss />
            <TbBrandNextjs />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl font-bold py-1 pt-6 dark:text-white text-center my-4">
              Projects
            </h3>
            <p className="dark:text-white">
              Here are some of the{" "}
              <span className="text-teal-500"> projects</span> that I've built.
            </p>
          </div>
          <div className="lg:flex gap-10 justify-center items-center">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-teal-600 dark:text-white flex-1">
              <Image
                src={expenseTracker}
                width={100}
                height={100}
                className="mx-auto"
              />
              <a href="https://expense-tracker-nm.netlify.app">
                <h3 className="text-lg font-bold pt-4 pb-2 text-teal-600 dark:text-black dark:border-white">
                  Expense Tracker
                </h3>
              </a>

              <p className="mb-4">
                {" "}
                An Expense Tracker app built with React. Allows the user to add
                expenses and earnings and retrieve the net result.
              </p>
              <a
                href="#"
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-1 rounded-md mt-2 dark:bg-black"
              >
                Code
              </a>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-teal-600 dark:text-white flex-1">
              <Image
                src={jobFinder}
                width={100}
                height={100}
                className="mx-auto"
              />
              <a href="https://jobfinderbyniwizmo.netlify.app">
                <h3 className="text-lg font-bold pt-4 pb-2 text-teal-600 dark:text-black">
                  JobFinder
                </h3>
              </a>
              <p className="mb-4">
                {" "}
                JobFinder is a demo UI for a job searching app, built with Vite
                ReactJs and Tailwind CSS.
              </p>
              <a
                href="#"
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-1 rounded-md mt-2 dark:bg-black"
              >
                Code
              </a>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-teal-600 dark:text-white flex-1">
              <Image src={jaaro} width={100} height={100} className="mx-auto" />
              <a href="https://jaaro.netlify.app">
                <h3 className="text-lg font-bold pt-4 pb-2 text-teal-600 dark:text-black">
                  jaarO
                </h3>
              </a>
              <p className="mb-4">
                {" "}
                jaarO is a static landing page built with React.js and Framer
                framework.
              </p>
              <a
                href="#"
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-1 rounded-md mt-2 dark:bg-black"
              >
                Code
              </a>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-600 dark:text-white flex-1">
              <Image
                src={memeGen}
                width={100}
                height={100}
                className="mx-auto"
              />
              <a href="https://meme-generator-nmm.netlify.app">
                <h3 className="text-lg font-bold pt-4 pb-2 text-teal-600 dark:text-black">
                  Meme Generator
                </h3>
              </a>
              <p className="mb-4">
                {" "}
                Meme Generator is a simple React application that generates
                random meme templates where the user can add texts.
              </p>
              <a
                href="#"
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-1 rounded-md mt-2 dark:bg-black"
              >
                Code
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
